apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.clusterName }}-external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: {{ .Values.versions.externalSecrets }}
    chart: external-secrets
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true

        # ServiceAccount (sin IAM por ahora)
        serviceAccount:
          create: true
          name: external-secrets-sa
          # TODO: Agregar annotation con IAM role ARN cuando esté listo
          # annotations:
          #   eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT:role/ROLE_NAME"

        # Recursos recomendados
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

        # Webhook configuration
        webhook:
          port: 9443

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignorar diferencias comunes en webhooks
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
