apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.clusterName }}-goldilocks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default

  source:
    repoURL: https://charts.fairwinds.com/stable
    targetRevision: {{ .Values.versions.goldilocks }}
    chart: goldilocks
    helm:
      releaseName: goldilocks
      values: |
        # Dashboard configuration (recursos reducidos para cluster local)
        dashboard:
          enabled: true
          replicaCount: {{ .Values.goldilocks.replicaCount }}
          service:
            type: ClusterIP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi

        # Controller configuration (recursos reducidos para cluster local)
        controller:
          enabled: true
          replicaCount: {{ .Values.goldilocks.replicaCount }}
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi

        # VPA (Vertical Pod Autoscaler)
        vpa:
          enabled: {{ .Values.goldilocks.installVpa }}

  destination:
    server: {{ .Values.clusterServer }}
    namespace: goldilocks

  syncPolicy:
    # Sync manual para control de despliegue
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
