apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.clusterName }}-kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: {{ .Values.versions.kyverno }}
    chart: kyverno
    helm:
      releaseName: kyverno
      values: |
        # Features
        features:
          forceFailurePolicyIgnore:
            enabled: true

        # Admission Controller
        admissionController:
          enabled: true
          replicas: {{ .Values.kyverno.replicaCount }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi

        # Background Controller
        backgroundController:
          enabled: true
          replicas: {{ .Values.kyverno.replicaCount }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi

        # Cleanup Controller
        cleanupController:
          enabled: true
          replicas: {{ .Values.kyverno.replicaCount }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi

        # Reports Controller
        reportsController:
          enabled: true
          replicas: {{ .Values.kyverno.replicaCount }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignorar diferencias en webhooks
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
