apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.clusterName }}-metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: {{ .Values.versions.metricsServer }}
    chart: metrics-server
    helm:
      releaseName: metrics-server
      values: |
        # Args para EKS
        args:
          - --kubelet-preferred-address-types=InternalIP
          - --kubelet-use-node-status-port
          - --metric-resolution=15s

        # Recursos
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 1Gi

        # High availability
        replicas: 2

        # Pod disruption budget
        podDisruptionBudget:
          enabled: true
          minAvailable: 1

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
