apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.clusterName }}-metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: {{ .Values.versions.metricsServer }}
    chart: metrics-server
    helm:
      releaseName: metrics-server
      values: |
        # Args para cluster local (ajustado para desarrollo)
        args:
          - --kubelet-preferred-address-types=InternalIP
          - --kubelet-use-node-status-port
          - --metric-resolution=15s
          - --kubelet-insecure-tls  # Para clusters locales sin certificados válidos

        # Recursos reducidos para cluster local (2 CPU / 3 GB RAM)
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi

        # Single replica para cluster local
        replicas: 1

        # Pod disruption budget deshabilitado (no necesario con 1 replica)
        podDisruptionBudget:
          enabled: false

  destination:
    server: {{ .Values.clusterServer }}
    namespace: kube-system

  syncPolicy:
    # Sync manual para control de despliegue
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
